### PR TITLE
Contributed_New_Questions_by_Chaitanya

### PR DESCRIPTION
**Pull request by Chaitanya985074**
Added some more questions hope it helps

### CODE REVIEW

**Comment by Jaspreet-singh-1032** [comment]
Thanks, @Chaitanya985074, for adding the questions. Can you look at the structure of other questions and add the full description in the question itself? The goal is that people don't have to visit external sites and can view the whole question detail in the VS code itself. The link is useful in case they want to try it on external platform or view the solution.

**Comment by Chaitanya985074** [comment]
Ok I will do that

**Comment by Chaitanya-Panicker** [comment]
Please check i have added the questions

**Comment by Jaspreet-singh-1032** [comment]
Let's close this PR since you have added questions in the other PR.

**Pull request closed without merging**
